import type { Metadata } from "next";
import Navbar from "./components/Navbar"; 
import { Exo_2 } from "next/font/google";
import "./globals.css";

const exo = Exo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Alure Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} antialiased`}
      >
        <div className="sm:px-10 px-5 py-0.5 font-medium space-x-3 text-right">
            <a href="https://bnbmc.net" className="transition duration-150 ease-out hover:ease-in md:hover:text-red-500">bnbmc.net ↗</a>
            <a href="https://alee14.me" className="transition duration-150 ease-out hover:ease-in md:hover:text-green-500">alee14.me ↗</a>
        </div>
        <Navbar />
        {children}
        <footer className="flex flex-col text-center py-3 space-y-2 bg-blue-950 text-light text-sm sm:text-base px-5 sm:px-0">
            <p>Alure Post is a fictional company made for the bits & Bytes Minecraft Server</p>
            <p>This website is proudly written using Next.JS and Tailwind CSS</p>
        </footer>
      </body>
    </html>
  );
}
